### ISSUE TITLE
Issues / suggested changes after the initial beta version

### ISSUE THREAD

**Issue by DanielBatesJ** [Krzyhau/Portal2SpeedrunMod#1]
Bugs:
Game crash: https://clips.twitch.tv/JollyHungryPastaPrimeMe (could be an issue with the game, and not the mod, but I have a feeling it could relate to the funnel somehow)
Getting stuck in the elevator on Repulsion Intro -Betsruner

Suggestions:
Faster opening elevators at the end of levels
Three gels faster elevator -Betsruner
Triggering lights for Repulsion Intro first elevator early.
Speed up literally every door if possible -Betsruner
Enlarging the trigger at the start of Laser Relays, so going too fast before the level load doesn't leave you with an untriggered door at the start of the map.
Some sort of indicator that you can leave the Wheatley elevator in Wakeup -Betsruner

**Comment by Krzyhau** [comment]
Most of suggestions are added. RepIntro bug fixed. Game crash most likely cause by saveloading and recording within Finale 3 - the game doesn't like that for some reason lol.
