### ISSUE TITLE
open the thing

### ISSUE THREAD

**Issue by Kamistiman** [Krzyhau/Portal2SpeedrunMod#3]
I probably missed something and am stupid but how do you open it? Do you swap a file with the Portal 2 files or something else?

**Comment by Krzyhau** [comment]
There's a README.txt file in every release zip file, which says how to install and run the mod. You unpack the "Portal 2 Speedrun Mod" folder into your "sourcemods" directory, then restart Steam. A new game called "Portal 2 Speedrun Mod" should be available in your Steam library. But fair point, maybe I should put installation tutorial literally everywhere so you cannot miss it lmao

**Comment by Kamistiman** [comment]
Thank you
