### ISSUE TITLE
Every category is fog%... Any fix?

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [Krzyhau/Portal2SpeedrunMod#5]
Tried reinstalling. Sadly didn't work... Any advice?

EDIT: I found out that there's only fog every other chamber and for every other chamber that doesn't have fog, there isn't any dialogue... sort of a mix of all categories.

**Comment by Krzyhau** [comment]
Are you sure that you didn't accidentally download a source code? If so, reinstall the mod using the newest zip package from `releases` tab.

From what you describe I assume that SMSM plugin is not loaded, which is an essential part of this mod.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I originally downloaded the mod from the resources tab on speedrun.com, but I'll try downloading it from the releases tab from here.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I'm still having issues with trying to get it to work, I downloaded the mod from the releases tab and tried it but still didn't work. Do you know of anything else I could be doing wrong?

**Comment by Krzyhau** [comment]
Make sure that you're installing the mod properly. Some people just put it into Portal 2 folder and expect it to work while it's not a correct way of doing it at all. Also make sure that SMSM plugin is loaded. You can easily recognize that by looking if background in main menu is changed into Wheatley in space. If it's not, then open up the developer console and look for any plugin-related messages/errors.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
> Make sure that you're installing the mod properly. Some people just put it into Portal 2 folder and expect it to work while it's not a correct way of doing it at all. Also make sure that SMSM plugin is loaded. You can easily recognize that by looking if background in main menu is changed into Wheatley in space. If it's not, then open up the developer console and look for any plugin-related messages/errors.

Well I use linux so I know that the version that came with the rest of the mod wouldn't work because that version is windows only (.dll) but idk if there's a version for linux (.so) in which I use...

**Comment by Krzyhau** [comment]
Yeah, that explains a lot. As I previously said, the plugin is an essential part of a mod. It controls stuff like mode type, custom background, mode-specific stuff that cannot be done using scripts etc. Basically it won't work properly without it. Unfortunately, there's no linux version of that plugin for now, but I'll try my best to build one for the next version of the mod.

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
Hey, I'm reopening this issue today just 'cause I noticed in the credits in the code tab that Nekz was actually helped with the smsm.dll plugin/file/idk and I was wondering if you could ask him if its possible to make a version of the smsm file that is supported on linux (.so)...

Hope you aren't too bothered with me having to reopen this issue...
